engines/engine1/config/routes.rb
Engine1::Engine.routes.draw do
  resources :another_models

end

engines/engine1/app/models/engine1/another_model.rb
module Engine1
  class AnotherModel < ActiveRecord::Base
      include Wisper::Publisher

      after_update { |me| broadcast(:updated_another_model, me) if me.id.even? }

  end
end

engines/engine1/app/controllers/engine1/another_models_controller.rb
require_dependency "engine1/application_controller"

module Engine1
  class AnotherModelsController < ApplicationController
    include Wisper::Publisher

    before_action :set_another_model, only: [:show, :edit, :update, :destroy]

    # GET /another_models
    def index
      @another_models = AnotherModel.all
    end

    # GET /another_models/1
    def show
    end

    # GET /another_models/new
    def new
      @another_model = AnotherModel.new
    end

    # GET /another_models/1/edit
    def edit
    end

    # POST /another_models
    def create
      @another_model = AnotherModel.new(another_model_params)

      if @another_model.save
        broadcast(:engine1_another_model_created, @another_model)
        redirect_to @another_model, notice: 'Another model was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /another_models/1
    def update
      if @another_model.update(another_model_params || {})
        redirect_to @another_model, notice: 'Another model was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /another_models/1
    def destroy
      @another_model.destroy
      redirect_to another_models_url, notice: 'Another model was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_another_model
        @another_model = AnotherModel.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def another_model_params
        params[:another_model]
      end
  end
end

engines/engine1/app/controllers/engine1/application_controller.rb
module Engine1
  class ApplicationController < ActionController::Base
  end
end

engines/engine1/app/helpers/engine1/another_models_helper.rb
module Engine1
  module AnotherModelsHelper
  end
end

engines/engine1/app/helpers/engine1/application_helper.rb
module Engine1
  module ApplicationHelper
  end
end

engines/engine1/app/views/engine1/another_models/_form.html.erb
<%= form_for(@another_model) do |f| %>
  <% if @another_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@another_model.errors.count, "error") %> prohibited this another_model from being saved:</h2>

      <ul>
      <% @another_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

engines/engine1/app/views/engine1/another_models/edit.html.erb
<h1>Editing another_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @another_model %> |
<%= link_to 'Back', another_models_path %>

engines/engine1/app/views/engine1/another_models/index.html.erb
<h1>Listing another_models</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @another_models.each do |another_model| %>
      <tr>
        <td><%= link_to 'Show', another_model %></td>
        <td><%= link_to 'Edit', edit_another_model_path(another_model) %></td>
        <td><%= link_to 'Destroy', another_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Another model', new_another_model_path %>

engines/engine1/app/views/engine1/another_models/new.html.erb
<h1>New another_model</h1>

<%= render 'form' %>

<%= link_to 'Back', another_models_path %>

engines/engine1/app/views/engine1/another_models/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_another_model_path(@another_model) %> |
<%= link_to 'Back', another_models_path %>

engines/engine1/app/views/layouts/engine1/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Engine1</title>
  <%= stylesheet_link_tag    "engine1/application", media: "all" %>
  <%= javascript_include_tag "engine1/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>