config/routes.rb
Rails.application.routes.draw do
  resources :my_models
  mount Engine1::Engine, at: '/engine1'

end

app/models/my_model.rb
class MyModel < ActiveRecord::Base
    include Wisper::Publisher

    after_create { |me| broadcast(:send_mail, me) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_models_controller.rb
class MyModelsController < ApplicationController
  include Wisper::Publisher

  before_action :set_my_model, only: [:show, :edit, :update, :destroy]

  # GET /my_models
  # GET /my_models.json
  def index
    @my_models = MyModel.all
  end

  # GET /my_models/1
  # GET /my_models/1.json
  def show
  end

  # GET /my_models/new
  def new
    @my_model = MyModel.new
  end

  # GET /my_models/1/edit
  def edit
  end

  # POST /my_models
  # POST /my_models.json
  def create
    @my_model = MyModel.new(my_model_params)

      if @my_model.save
        broadcast(:create_model_success, @my_model)
        redirect_to @my_model, notice: 'My model was successfully created.'
      else
        broadcast(:create_model_error, @my_model)
        render :new

      end
  end

  # PATCH/PUT /my_models/1
  # PATCH/PUT /my_models/1.json
  def update
      if @my_model.update(my_model_params || {})
          broadcast(:edit_model_success, @my_model)
          redirect_to @my_model, notice: 'My model was successfully updated.'
      else
          broadcast(:edit_model_error, @my_model)
          render :edit
      end
  end

  # DELETE /my_models/1
  # DELETE /my_models/1.json
  def destroy
    @my_model.destroy
    broadcast(:model_destroyed)
    redirect_to my_models_url, notice: 'My model was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_model
      @my_model = MyModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_model_params
      params[:my_model]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_models_helper.rb
module MyModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WisperMailing</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="flash"><strong>Wisper: </strong><br><%= MESSAGES.join('<br>').html_safe %></div>
<%= yield %>

</body>
</html>

app/views/my_models/_form.html.erb
<%= form_for(@my_model) do |f| %>
  <% if @my_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_model.errors.count, "error") %> prohibited this my_model from being saved:</h2>

      <ul>
      <% @my_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_models/edit.html.erb
<h1>Editing my_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_model %> |
<%= link_to 'Back', my_models_path %>

app/views/my_models/index.html.erb
<h1>Listing my_models</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_models.each do |my_model| %>
      <tr>
        <td><%= link_to 'Show', my_model %></td>
        <td><%= link_to 'Edit', edit_my_model_path(my_model) %></td>
        <td><%= link_to 'Destroy', my_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My model', new_my_model_path %>

app/views/my_models/new.html.erb
<h1>New my_model</h1>

<%= render 'form' %>

<%= link_to 'Back', my_models_path %>

app/views/my_models/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_my_model_path(@my_model) %> |
<%= link_to 'Back', my_models_path %>